module.exports = [
{ id:'virtualization', ch:4, term:'仮想化', read:'バーチャライゼーション・仮想化技術', icon:'FaObjectUngroup', lay:['virt'], sup:true,
  one:'1台の機械を、ソフトの力で複数の独立した環境に分けて使う技術。',
  what:[
    '仮想化は、1台の本物の機械（物理サーバー）を、ソフトで「何台かの別々のコンピューター」に見せる技術です。分けた1つ1つを仮想マシン（VM）と呼びます。',
    'やり方は大きく2つです。OSごと分けるVM型と、アプリごと箱に詰めるコンテナ型です。目的は、CPUやメモリの使い残しをなくし、用途ごとに環境を分けて管理しやすくすることです。',
    '分けた環境は、作る・コピーする・消すがソフトの操作だけで済みます。機械を買い足すより速く、クラウドもこの仮想化の上に成り立っています。' ],
  ana:'1台に1用途なら一戸建て。仮想化は、大きなマンションを部屋ごとに貸す方式で、物理サーバーがマンション、分けた環境が各部屋です。',
  scene:'Windows PCの中でLinuxを試す、会社が10個の小さなシステムを数台のサーバーにまとめる、といった場面で使われます。',
  where:'ハードウェアとOSの上で、機械を分けて使うための層。',
  rel:[ {to:'hypervisor',label:'実現する',dir:'in'}, {to:'vm',label:'作り出す',dir:'out'}, {to:'container',label:'別の方式',dir:'both'}, {to:'hardware',label:'分けて使う',dir:'out'}, {to:'cloud',label:'土台になる',dir:'out'} ],
  warn:'仮想化は「VMを作ること」だけではなく、コンテナも仮想化の仲間です。VMの実際の性能は、元の物理サーバーの性能が上限です。',
  learn:'タスクマネージャーの「パフォーマンス」→「CPU」で、自分のPCの「仮想化」が有効か確認しましょう。' },

{ id:'vm', ch:4, term:'仮想マシン（VM）', read:'ブイエム・Virtual Machine', icon:'FaDesktop', lay:['virt'], sup:false,
  one:'本物の機械の中に、ソフトで作る「もう1台のコンピューター」。',
  what:[
    '仮想マシン（VM）は、ソフトで作った架空のコンピューターです。CPU・メモリ・ディスクが本物のPCのように見えるので、WindowsやLinuxなどのOSをまるごと入れて動かせます。',
    '本物の機械（ホスト）の部品は、ハイパーバイザーが割り当てます。VMは仮想ディスクという大きなファイルとして保存されることが多く、コピーすれば増やせます。VMごとにOSを持つため、起動は遅めで、メモリも多く使います。' ],
  ana:'アパートの1室。部屋ごとに玄関・台所・風呂（＝OS）が独立し、隣に左右されませんが、設備が全部屋にあるぶん場所をとります。',
  scene:'PCの中で別のOSを試す、授業でLinuxを入れて壊してもやり直す、古いシステムを専用のVMに分けて動かす、といった場面です。',
  where:'サーバーやPCの中でソフトとして動く「仮想のコンピューター」。',
  rel:[ {to:'hypervisor',label:'作り出す',dir:'in'}, {to:'os',label:'OSを動かす',dir:'out'}, {to:'hardware',label:'部品を借りる',dir:'out'}, {to:'container',label:'ちがい',dir:'both'}, {to:'cloudvm',label:'土台になる',dir:'out'} ],
  warn:'VMは「アプリを入れただけ」ではなく、OSまで入った別のコンピューターです。VMごとにOSの更新や対策も必要です。',
  learn:'VirtualBoxなどでLinuxのVMを1台作り、起動・停止・削除を試しましょう。メモリ量を変えると動きが変わります。' },

{ id:'hypervisor', ch:4, term:'ハイパーバイザー', read:'Hypervisor・仮想化ソフト', icon:'FaThLarge', lay:['virt'], sup:false,
  one:'VMを作り、CPUやメモリを割り当てて動かす、仮想化の管理役。',
  what:[
    'ハイパーバイザーは、物理サーバーの上でVMを作って動かすソフトです。物理のCPUやメモリを各VMに「ここからここまで」と割り当て、VM同士が邪魔し合わないよう見張ります。',
    '機械に直接入れる「ベアメタル型」と、WindowsやMacにアプリとして入れる「ホスト型」があります。前者の例はVMware ESXi、後者の例はVirtualBoxです。サーバーでは前者が主に使われます。' ],
  ana:'アパートの管理会社。ビルを部屋に仕切り、入居者（VM）へ水道・電気（CPUやメモリ）を配り、隣へ迷惑をかけないよう調整します。',
  scene:'サーバー1台に10個のVMを載せるとき、「このVMはCPU2つ、メモリ4GB」と設定する場面です。VMソフトの裏でも働いています。',
  where:'ハードウェアとVMの間で動く、仮想化専用の管理ソフト。',
  rel:[ {to:'vm',label:'作り出す',dir:'out'}, {to:'hardware',label:'分けて配る',dir:'out'}, {to:'virtualization',label:'実現する',dir:'out'}, {to:'kvm',label:'具体例',dir:'in'}, {to:'hyperv',label:'具体例',dir:'in'} ],
  warn:'ハイパーバイザーはVMそのものではなく、VMを作って動かす側です。割り当てを増やしすぎると、同時に使ったとき全体が遅くなります。',
  learn:'VMソフトでCPU数とメモリ量を変えて起動し、VM内のタスクマネージャーなどで数字が変わるのを確かめましょう。' },

{ id:'container', ch:4, term:'コンテナ', read:'Container・コンテナ型仮想化', icon:'FaBoxes', lay:['virt'], sup:true,
  one:'アプリと必要な部品を箱に詰め、OSを共有して軽く動かす技術。',
  what:[
    'コンテナは、アプリと必要な部品（ライブラリや設定）を1つにまとめ、他から隔離して動かす仕組みです。OSの中心部分（カーネル）は、同じ機械上のコンテナ同士で共有します。',
    '住まいにたとえると、VMはアパート、コンテナは台所と風呂を共用するシェアハウスです。OSを持たないぶん小さく、起動も短時間で、1台で多数を動かせます。ただし隔離の強さはVMと違います。',
    'コンテナの中身は「イメージ」という設計図から作り、Dockerなどのツールで動かします。多数のコンテナはKubernetesなどで管理します。' ],
  ana:'コンテナ船の貨物コンテナ。中身が何でも規格の同じ箱に入れれば、船でもトラックでも同じように運べます。船が機械、箱がアプリです。',
  scene:'チームで開発するとき、「自分のPCでは動くのに他の人では動かない」を防ぐため、全員が同じコンテナを起動する場面です。',
  where:'OSの上で、アプリごとに隔離して動かす層（仮想化の一種）。',
  rel:[ {to:'docker',label:'作って動かす',dir:'in'}, {to:'vm',label:'ちがい',dir:'both'}, {to:'os',label:'OSを共有',dir:'out'}, {to:'k8s',label:'管理する',dir:'in'}, {to:'deploy',label:'配置の単位',dir:'out'} ],
  warn:'コンテナはVMの小型版ではありません。OSの中心部分を共有するので、Linuxのコンテナは、Linuxのカーネル上で動きます。',
  learn:'「VMはアパート、コンテナはシェアハウス」の図を描き、共有する部分と別々の部分を書き分けましょう。' },

{ id:'docker', ch:4, term:'Docker', read:'ドッカー', icon:'FaDocker', lay:['virt'], sup:false,
  one:'アプリを開発し、配り、動かすための、コンテナを使ったオープンなプラットフォーム。',
  what:[
    'Dockerは、アプリをコンテナという隔離された環境に入れて、開発・配布・実行するためのプラットフォームです。アプリを動かす環境（インフラ）から切り離し、素早く届けられます。',
    '基本の部品は3つ。設計図の「イメージ」、それから動かす実体の「コンテナ」、イメージの置き場の「レジストリ（Docker Hubなど）」です。イメージはDockerfileという手順書から作ります。',
    '操作は、dockerコマンド（クライアント）が、裏で動くDockerデーモン（dockerd）に指示する形です。コンテナは手元のPC、サーバー、クラウドのどこにも置けます。' ],
  ana:'設計図と製品の関係。イメージが設計図、コンテナがそれから作った実物、レジストリが設計図の保管庫。同じ設計図から何個でも作れます。',
  scene:'授業で先生が配ったイメージを「docker run」で起動するだけで、全員が同じ開発環境を用意できる場面です。公開（デプロイ）にも使います。',
  where:'開発者のPCやサーバーの上で動く、コンテナを扱うツール群。',
  rel:[ {to:'container',label:'作って動かす',dir:'out'}, {to:'apserver',label:'箱に詰める',dir:'out'}, {to:'deploy',label:'配置を楽にする',dir:'out'}, {to:'k8s',label:'コンテナを渡す',dir:'out'}, {to:'linux',label:'機能を使う',dir:'out'} ],
  warn:'Dockerはコンテナそのものではなく、扱うための製品名です。WindowsやMacのDocker Desktopでは、裏でLinuxの仮想環境が動きます。',
  learn:'Docker Desktopを入れて「docker run hello-world」を実行しましょう。動いたら、自分のアプリのDockerfileを書きます。',
  quote:'Dockerは、コンテナによるアプリの開発・実行を支えます（貼り付けの記載）。' },

{ id:'k8s', ch:4, term:'Kubernetes', read:'クバネティス（K8s）', icon:'FaDharmachakra', lay:['virt'], sup:false,
  one:'多数のコンテナを、どの機械でどう動かすか自動で管理する仕組み。',
  what:[
    'Kubernetes（クバネティス、K8s）は、コンテナ化したアプリを管理するオープンソースの基盤です。「3つ動かしておく」と望む状態を書けば、実際の状態をそれに合わせ続けます。',
    '止まったコンテナは再起動し、負荷は分散し、設定すればアクセス増加で数も増やします。複数の機械（ノード）を束ねたものがクラスターで、コンテナはPod（入れ物）の単位で空いた機械へ自動配置されます。' ],
  ana:'コンテナ船団の運行管理者。どの船（機械）にどの箱を積むかを決め、故障した船の箱は別の船へ積み替えます。',
  scene:'アクセスが集中するネットのサービスで、コンテナ数を自動で増やし、サーバーが1台壊れても別のサーバーで動かし直す場面です。',
  where:'複数のサーバーにまたがり、コンテナを配置・運用する管理基盤。',
  rel:[ {to:'container',label:'管理する',dir:'out'}, {to:'docker',label:'コンテナを渡す',dir:'in'}, {to:'deploy',label:'自動で配置',dir:'out'}, {to:'managed',label:'提供する',dir:'in'} ],
  warn:'KubernetesはDockerの代わりではなく、コンテナを多数動かすときの運用管理を担います。数個なら不要なことも多く、学ぶ範囲も広めです。',
  learn:'Dockerを学んだ後、公式のMinikubeを使う入門チュートリアルで、小さなアプリを動かしPodの数を変えてみましょう。',
  quote:'Kubernetesは、コンテナ化したアプリの管理を担います（貼り付けの記載）。公式資料では、スケーリングや障害時の復旧（フェイルオーバー）を扱うと説明されています。' },

{ id:'vmware', ch:4, term:'VMware', read:'ヴイエムウェア', icon:'FaClone', lay:['virt'], sup:false,
  one:'仮想化製品群の名前。サーバー用のESXiや、PC用のWorkstationなどがある。',
  what:[
    'VMwareは、仮想化に関する製品の名前（ブランド）です。サーバーに直接入れてVMを動かす「ESXi」が基本の製品で、企業のサーバー室やデータセンターで使われます。',
    'ESXiの管理ソフト「vCenter Server」などを含む製品群が「vSphere」です。PC用には、Windows・Linux向けのWorkstation、Mac向けのFusionがあり、OSの上にアプリとして入れて使います。' ],
  ana:'自動車メーカー名のような存在。メーカー名（VMware）の下に、ESXiやvSphereなど「車種」（製品）が並びます。',
  scene:'ITの求人や社内の構成図に「VMware環境」「vSphere」と書かれる場面です。仮想化基盤を作る・運用する仕事で名前が出ます。',
  where:'企業のサーバー室やデータセンターで、VMを動かす仮想化ソフト。',
  rel:[ {to:'hypervisor',label:'ESXiを提供',dir:'out'}, {to:'vm',label:'動かす',dir:'out'}, {to:'kvm',label:'同じ仲間',dir:'both'}, {to:'hyperv',label:'同じ仲間',dir:'both'}, {to:'datacenter',label:'で使われる',dir:'out'} ],
  warn:'VMwareは1つの製品名ではなく、製品群の名前です。「VMware」と言われたら、ESXi・vSphere・Workstationのどれか確認しましょう。',
  learn:'VMとハイパーバイザーを理解した後、職場や学校でどの製品が使われているか調べ、ESXiとvSphereの違いを図にしましょう。' },

{ id:'openstack', ch:4, term:'OpenStack', read:'オープンスタック', icon:'FaCogs', lay:['virt','cloud'], sup:false,
  one:'サーバー・保存装置・ネットワークをまとめ、クラウド環境を作るオープンソースのソフト群。',
  what:[
    'OpenStackは、多数のサーバー・ストレージ・ネットワークを「資源の集まり」にまとめ、APIやWeb画面から申し込むだけで使えるようにするオープンソースのソフト群です。',
    '「VMがほしい」と画面で頼むと、空いたサーバーを探してVMを作ります。VMはNova、ディスクはCinder、ネットワークはNeutronと、役割ごとの部品を組み合わせます。自社設備にプライベートクラウドを作る用途などで使われます。' ],
  ana:'ホテルのフロント。客室（サーバー）の空きを管理し、「部屋をください」の注文に、すぐ部屋（VM）を用意して渡します。',
  scene:'大学や企業が、自前のサーバー群の上に「申し込めばすぐVMが使える」社内向けの窓口を作る場面です。',
  where:'サーバー室やデータセンターの設備をまとめて管理する基盤ソフト。',
  rel:[ {to:'vm',label:'作って渡す',dir:'out'}, {to:'private',label:'構築に使う',dir:'out'}, {to:'hypervisor',label:'土台になる',dir:'in'}, {to:'datacenter',label:'設備をまとめる',dir:'out'}, {to:'linux',label:'土台になる',dir:'in'} ],
  warn:'OpenStackは申し込んで使うクラウドサービスではなく、クラウドを作る側のソフトです。入れるだけでは使えず、設備と運用する人が必要です。',
  learn:'LinuxとVMの基本を学んでから、学習用の小規模構成で、Web画面からVMを1台作る手順をなぞってみましょう。' },

{ id:'kvm', ch:4, term:'KVM', read:'ケーブイエム（Kernel-based Virtual Machine）', icon:'FaLinux', lay:['virt','os'], sup:false,
  one:'Linuxに組み込まれた、Linux自身をハイパーバイザーにする仮想化機能。',
  what:[
    'KVM（Kernel-based Virtual Machine）は、Linuxのカーネル（OSの中心部分）に組み込まれた仮想化の機能です。これにより、Linux自身がVMを動かすハイパーバイザーとして働きます。',
    'CPUに備わった仮想化の支援機能を使い、VMを効率よく動かします。仮想のディスクなどの部品は、QEMUというソフトと組み合わせて用意するのが一般的です。OpenStackなどの基盤でも使われます。' ],
  ana:'ビルの管理人室を別に作らず、ビル（Linux）自体が管理人を兼ねる状態。家主が管理人もする、というイメージです。',
  scene:'Linuxサーバー1台に複数のVMを載せたいときや、OpenStackなどの基盤でVMを実際に動かす部品として使われる場面です。',
  where:'Linux（OS）の内部にある仮想化の機能。OSとハイパーバイザーを兼ねる。',
  rel:[ {to:'linux',label:'組み込まれる',dir:'out'}, {to:'hypervisor',label:'として働く',dir:'out'}, {to:'vm',label:'動かす',dir:'out'}, {to:'openstack',label:'部品になる',dir:'out'}, {to:'hyperv',label:'同じ仲間',dir:'both'} ],
  warn:'KVMだけでVMが使いやすくなるわけではありません。QEMUや管理ツールと組み合わせ、CPUの仮想化機能をオンにする必要もあります。',
  learn:'Ubuntuなど対応するLinuxで、virt-managerなどを使いVMを1台作りましょう。lscpuで仮想化対応も確認できます。' },

{ id:'hyperv', ch:4, term:'Hyper-V', read:'ハイパーブイ', icon:'FaWindows', lay:['virt','os'], sup:false,
  one:'Microsoftの仮想化技術。Windows ServerやWindowsの機能としてVMを動かせる。',
  what:[
    'Hyper-V（ハイパーブイ）は、Microsoftの仮想化技術です。Windows Serverの機能として、またWindows 11のProなど一部のエディションの機能として提供され、VMを作って動かせます。',
    '機械に直接入るタイプ1型のハイパーバイザーです。機能をオンにすると、Hyper-VマネージャーからLinuxなどのVMも作れます。使うにはCPUの仮想化機能がオンである必要があります。' ],
  ana:'Windowsに用意された「仮想の部屋づくりキット」。機能をオンにすれば、PCやサーバーの中に部屋（VM）を作って貸し出せます。',
  scene:'会社のWindowsサーバー1台で複数のVMを動かす、Windows 11のPCで安全にLinuxを試す、といった場面で使われます。',
  where:'Windowsに備わった仮想化の機能。Windows ServerやPro以上で使う。',
  rel:[ {to:'windows',label:'組み込まれる',dir:'out'}, {to:'hypervisor',label:'として働く',dir:'out'}, {to:'vm',label:'動かす',dir:'out'}, {to:'kvm',label:'同じ仲間',dir:'both'}, {to:'vmware',label:'同じ仲間',dir:'both'} ],
  warn:'Windowsの「Home」では通常Hyper-Vは使えず、ProやEnterpriseなど使えるエディションが限られます。使う前に確認しましょう。',
  learn:'対応Windowsで「Windowsの機能の有効化または無効化」からHyper-Vをオンにし、小さなLinuxのVMを作りましょう。' },

{ id:'private', ch:4, term:'プライベートクラウド', read:'Private Cloud', icon:'FaBuilding', lay:['cloud','virt'], sup:true,
  one:'特定の組織だけが専用に使う、クラウドの仕組みで作った環境。',
  what:[
    'プライベートクラウドは、特定の1つの組織だけが使うクラウド環境です。クラウドとは、申し込めばすぐ必要な分だけ使えるIT資源の仕組みで、その利用者が組織内（部署など）に限られます。',
    '置き場所は2通り。自社のサーバー室やデータセンターに設備を置く形と、外部事業者の専用設備を借りる形です。どちらも他の組織と共用しません。VMwareやOpenStackなどで作られます。',
    '自社で運用する場合、設計の自由度は高い一方、設備の購入や保守、運用の負担は組織が負います。外部の専用環境では、運用を事業者が受け持つこともあります。' ],
  ana:'会社専用の社員食堂。外の人は使えず、席や設備を自社で決められますが、建物や調理の人手は自分たちで用意します。',
  scene:'個人情報など外に出したくないデータを扱う会社が、自社設備に社内向けクラウドを作り、各部署が申し込んでVMを使う場面です。',
  where:'特定の組織専用の環境。自社のサーバー室か、外部の専用設備にある。',
  rel:[ {to:'public',label:'ちがい',dir:'both'}, {to:'openstack',label:'構築に使う',dir:'in'}, {to:'vmware',label:'構築に使う',dir:'in'}, {to:'datacenter',label:'置き場所',dir:'in'}, {to:'cloud',label:'の一種',dir:'out'} ],
  warn:'自社にサーバーがあるだけでは、プライベートクラウドとは呼びません。申し込むとすぐ使える、使用量を管理できるなどの仕組みが必要です。',
  learn:'パブリッククラウドとの違いを、「設備は誰のものか」「誰が使うか」「誰が運用するか」の3項目の表にしましょう。' },

{ id:'cloud', ch:5, term:'クラウド', read:'クラウドコンピューティング', icon:'FaCloud', lay:['cloud'], sup:true,
  one:'ネット経由で、必要なときに必要な分だけ借りて使うITの仕組み。',
  what:[
    'クラウドは、サーバー・保存場所・データベースなどのIT資源を、自分で買わず、インターネット経由で借りて使う仕組みです。必要なとき増やし、不要になれば返せます。',
    '提供会社が巨大なデータセンターの機械を仮想化で分け、多数の利用者に貸します。貸し方は3段階。VMだけ借りる、アプリの動作環境まで借りる、完成したアプリ（Gmailなど）を使うだけ、です。借りる範囲が広いほど、自分の管理は減ります。' ],
  ana:'電気や水道。自分で発電所を持たなくても使え、使った分だけ払います。クラウドは「ITの電気」のように使えるサービスです。',
  scene:'スマホの写真が自動でネットに保存される、学校で共有ドキュメントを同時に編集する、開発者がサーバーを借りる、といった場面です。',
  where:'インターネットの向こう側にある、事業者の設備とサービス。',
  rel:[ {to:'virtualization',label:'土台になる',dir:'in'}, {to:'datacenter',label:'支える',dir:'in'}, {to:'internet',label:'経由で使う',dir:'out'}, {to:'public',label:'の一種',dir:'out'}, {to:'private',label:'の一種',dir:'out'} ],
  warn:'クラウドは保存場所だけを指す言葉ではありません。計算するサーバーやデータベースも含み、使った分の料金がかかる形が基本です。',
  learn:'使っているサービスを3つ選び、「データはどこにあり、誰の設備か」を調べて書き出してみましょう。' },

{ id:'public', ch:5, term:'パブリッククラウド', read:'Public Cloud', icon:'FaGlobe', lay:['cloud'], sup:false,
  one:'提供会社が、多数の顧客に向けて貸し出すクラウド。',
  what:[
    'パブリッククラウドは、提供会社が、企業・学校・個人など多数の顧客に向けて提供するクラウドです。設備は提供会社のもので、契約すれば誰でも使い始められます。',
    '複数の顧客が同じ物理設備を共用しますが、仮想化や権限管理で、他の顧客のデータが見えないよう分けられています。例はAWS・Azure・Google Cloudです。自社専用のプライベートクラウドとは、設備の持ち主と利用者の範囲が違います。' ],
  ana:'公共の貸し倉庫。建物は運営会社のもので、多くの人が同じ建物で自分の区画だけを借り、他人の区画には入れません。',
  scene:'スタートアップがサーバーを買わずにサービスを公開する、学生が学習用の環境を短時間だけ借りて試す、といった場面で使われます。',
  where:'インターネットの向こう側にある、事業者の設備を借りるサービス。',
  rel:[ {to:'private',label:'ちがい',dir:'both'}, {to:'aws',label:'一例',dir:'in'}, {to:'azure',label:'一例',dir:'in'}, {to:'gcp',label:'一例',dir:'in'}, {to:'datacenter',label:'置き場所',dir:'in'} ],
  warn:'この「パブリック」は、データが公開されるという意味ではありません。利用者が多数という意味です。設定を誤ると外から見える状態になります。',
  learn:'AWS・Azure・Google Cloudの入門ページで、サービスの種類（計算・保存・DBなど）を分類してみましょう。' },

{ id:'aws', ch:5, term:'AWS', read:'エーダブリューエス（Amazon Web Services）', icon:'FaAws', lay:['cloud'], sup:false,
  one:'Amazonが提供するパブリッククラウド。計算・保存・DBなど多数のサービスの総称。',
  what:[
    'AWS（Amazon Web Services）は、Amazonが提供するパブリッククラウドの名前です。サーバー、保存場所、データベース、ネットワーク、AIなど、非常に多くの種類のサービスの総称です。',
    '「AWS」という単一の製品はありません。サーバーは「Amazon EC2」、オブジェクトストレージは「Amazon S3」、データベースは「Amazon RDS」と、サービスごとに名前があります。世界各地で提供され、使う地域（リージョン）を選べます。' ],
  ana:'ITの総合レンタル店。貸しサーバー（EC2）も貸し倉庫（S3）も1つの契約で借りられ、使った分だけ支払います。',
  scene:'開発現場で「サーバーはAWSで動いています」と話す場面や、学習用にEC2でサーバーを1台立てる実習の場面です。',
  where:'インターネットの向こう側にある、Amazonのクラウドサービスの総称。',
  rel:[ {to:'public',label:'の一例',dir:'out'}, {to:'cloudvm',label:'提供する',dir:'out'}, {to:'s3',label:'提供する',dir:'out'}, {to:'awsdb',label:'提供する',dir:'out'} ],
  warn:'AWSはAmazonの通販サイトとは別のサービスです。同じ役割のサービスにも会社ごとに別名があります（サーバーはAzureならVirtual Machines）。',
  learn:'AWS公式の基礎教材で全体像をつかみ、学習用アカウントでサーバーを作って削除し、S3にファイルを入れてみましょう。' },

{ id:'azure', ch:5, term:'Azure', read:'アジュール', icon:'FaMicrosoft', lay:['cloud'], sup:false,
  one:'Microsoftが提供するパブリッククラウド。サーバー・DB・認証など多数のサービスの総称。',
  what:[
    'Azure（アジュール）は、Microsoftが提供するパブリッククラウドの名前です。仮想マシン、保存場所、データベース、AIなど、さまざまなサービスの総称で、世界各地のデータセンターで提供されます。',
    '例は、仮想マシンの「Azure Virtual Machines」、オブジェクトストレージの「Azure Blob Storage」、データベースの「Azure SQL Database」です。WindowsやMicrosoft 365、アカウント管理（Microsoft Entra ID）と連携する機能もあります。' ],
  ana:'IT部品の総合レンタル店の一つ。サーバー（仮想マシン）も倉庫（Blob Storage）もデータベースも、必要な分だけ借ります。',
  scene:'会社のWindowsサーバーの一部をAzureの仮想マシンに移す、社内システムのDBをAzure SQL Databaseで動かす、といった場面です。',
  where:'インターネットの向こう側にある、Microsoftのクラウドサービスの総称。',
  rel:[ {to:'public',label:'の一例',dir:'out'}, {to:'cloudvm',label:'提供する',dir:'out'}, {to:'cloudstorage',label:'提供する',dir:'out'}, {to:'windows',label:'連携する',dir:'both'} ],
  warn:'Azureは、Microsoft 365（Wordなどを使うサービス）とは別のサービスです。Azureはサーバーなどを借りる基盤です。',
  learn:'公式の入門教材で全体像を学び、学習用環境で仮想マシンとストレージを作って削除まで試しましょう。料金上限も確認します。' },

{ id:'gcp', ch:5, term:'Google Cloud', read:'グーグル・クラウド（GCP）', icon:'FaGoogle', lay:['cloud'], sup:false,
  one:'Googleが提供するパブリッククラウド。サーバー・データ分析・AIなどのサービスの総称。',
  what:[
    'Google Cloud（GCPと略されることもあります）は、Googleが提供するパブリッククラウドの名前です。サーバー、保存場所、データベース、AIなどのサービスを、使った分の料金で借りられます。',
    '例は、仮想マシンの「Compute Engine」、オブジェクトストレージの「Cloud Storage」、大量データを分析する「BigQuery」です。データ分析や機械学習のサービスが用意され、研究や分析の場面でも使われます。' ],
  ana:'IT部品の総合レンタル店の一つ。部屋（Compute Engine）・倉庫（Cloud Storage）・分析ラボ（BigQuery）が並びます。',
  scene:'大量のアクセスログを集めて分析する、研究室で計算用のVMを借りる、といった場面で名前が出ます。',
  where:'インターネットの向こう側にある、Googleのクラウドサービスの総称。',
  rel:[ {to:'public',label:'の一例',dir:'out'}, {to:'cloudvm',label:'提供する',dir:'out'}, {to:'cloudstorage',label:'提供する',dir:'out'}, {to:'analysis',label:'分析を支える',dir:'out'}, {to:'ai',label:'提供する',dir:'out'} ],
  warn:'Google Cloudはサーバーなどを借りる基盤サービスです。Gmailのように「使うだけ」のサービスとは役割が違います。',
  learn:'公式の入門教材で全体像を学び、学習用環境でサービスを1つ作って削除まで試しましょう。料金上限も確認します。' },

{ id:'cloudvm', ch:5, term:'クラウドの仮想サーバー', read:'EC2・Virtual Machines・Compute Engineなど', icon:'FaServer', lay:['cloud','virt'], sup:false,
  one:'クラウド上で借りる仮想のコンピューター。必要なときに作り、不要になれば削除する。',
  what:[
    'クラウドの仮想サーバーは、クラウド事業者の設備に作るVMを借りて使うサービスです。AWSではAmazon EC2、AzureではAzure Virtual Machines、Google CloudではCompute Engineがこれにあたります。',
    '画面でCPU数・メモリ・OSを選ぶと、VMが起動します。使い終えたら停止・削除できます。責任の分け方が大切で、サーバー本体と仮想化の部分は事業者、VM内のOS更新・アプリ・セキュリティ設定は利用者が管理します。' ],
  ana:'レンタルのパソコン。置き場所や電気、部品の故障対応は貸す会社が担当し、中にソフトを入れて設定する作業は借りた人がします。',
  scene:'Webサイトを公開するためLinuxのVMを借りてアプリを入れる、大きな計算のときだけ大きなVMを借りて終わったら削除する、といった場面です。',
  where:'クラウド事業者の設備の上に作られ、ネット経由で操作する仮想マシン。',
  rel:[ {to:'vm',label:'の一種',dir:'out'}, {to:'hypervisor',label:'上で動く',dir:'out'}, {to:'public',label:'提供する',dir:'in'}, {to:'managed',label:'ちがい',dir:'both'}, {to:'os',label:'自分で管理',dir:'out'} ],
  warn:'止め忘れると課金が続きます。OSの更新やセキュリティ設定は自分の担当で、「事業者が全部守ってくれる」わけではありません。',
  learn:'学習用アカウントで、作成→接続→停止→削除を体験しましょう。削除し忘れると料金が続くことがあります。' },

{ id:'cloudstorage', ch:5, term:'クラウドストレージ', read:'Cloud Storage', icon:'FaCloudUploadAlt', lay:['cloud','hw'], sup:false,
  one:'インターネット経由でデータを預ける、クラウド上の保存サービス。',
  what:[
    'クラウドストレージは、事業者のデータセンターにあるストレージ（保存装置）を、インターネット経由で借りて使うサービスです。自分の機械ではなく、ネットの向こうに預けます。',
    '大きく2種類あります。個人向けのファイル共有サービス（Googleドライブなど）と、アプリが使うストレージサービス（Amazon S3、Azure Blob Storage、Google Cloud Storage）です。多くは複数の機器に複製して保存し、誰が読み書きできるかは権限で設定します。' ],
  ana:'ネット上の貸し倉庫。家（PC）の外の倉庫に荷物（データ）を預け、鍵（権限）を渡した人だけがどこからでも出し入れできます。',
  scene:'スマホの写真が自動でバックアップされる、友達と共有フォルダーで資料を共同編集する、といった場面です。',
  where:'インターネットの向こう側にある、事業者の保存装置を使うサービス。',
  rel:[ {to:'s3',label:'一例',dir:'in'}, {to:'storage',label:'の一種',dir:'out'}, {to:'object',label:'主な方式',dir:'out'}, {to:'backup',label:'置き場になる',dir:'out'}, {to:'public',label:'提供する',dir:'in'} ],
  warn:'「クラウドに預けたからバックアップ済み」とは限りません。誤って削除したり、設定ミスで外から見える状態にすると、失う・漏えいすることがあります。',
  learn:'クラウドストレージにファイルを保存し、共有リンクの公開範囲（自分だけ・特定の人・全員）を変えて見え方を確かめましょう。' },

{ id:'managed', ch:5, term:'マネージドサービス', read:'Managed Service', icon:'FaHandsHelping', lay:['cloud','mw'], sup:false,
  one:'運用の手間の一部を、提供会社が代わりに担当してくれるクラウドのサービス。',
  what:[
    'マネージドサービスは、サーバーの保守、OSの更新、バックアップ、故障時の入れ替えなど「運用」の一部を、クラウドの提供会社が担当するサービスです。利用者は、使うことに集中できます。',
    '例は、データベースの「Amazon RDS」「Azure SQL Database」と、Kubernetesの「Amazon EKS」などです。担当範囲はサービスごとに違い、RDSではハードやOSの管理は事業者、表の設計とアクセス権の設定は利用者です。' ],
  ana:'掃除や点検つきの賃貸マンション。設備の修理や共用部の掃除は管理会社がしますが、部屋の使い方や持ち物は住む人の責任です。',
  scene:'Webアプリのデータベースを自分で入れず、RDSなどを申し込んで使い、夜間の更新作業や故障対応の負担を減らす場面です。',
  where:'クラウドの中で、提供会社が運用の一部を受け持つタイプのサービス。',
  rel:[ {to:'cloudvm',label:'ちがい',dir:'both'}, {to:'awsdb',label:'の一例',dir:'in'}, {to:'db',label:'運用を代行',dir:'out'}, {to:'k8s',label:'提供する',dir:'out'}, {to:'public',label:'提供する',dir:'in'} ],
  warn:'「マネージド＝全部おまかせ」ではありません。事業者の担当範囲はサービスごとに違い、データの中身・権限・設定は利用者の責任です。',
  learn:'使いたいサービスの公式ページで「責任共有モデル」を探し、事業者の担当と自分の担当を2列で書き出しましょう。' }
];
